# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/kth-ml-course-projects/iwae-pytorch/blob/main/src/GoogleCollab.ipynb

# Code to download IWAE data
"""

# Imports
import wget
from tqdm import tqdm
import gzip
import shutil
import os

# Functions
def unzip_gz(filepath):
  """
  Unzip a file located at filepath. The file is replaced by the unzipped version
  :param: filepath string path
  """
  # Open file with gzip encoding
  with gzip.open(filepath, 'rb') as f_in:
      # Uncompress the file and remove .gz ending
      with open(filepath[:-3], 'wb') as f_out:
          shutil.copyfileobj(f_in, f_out)

def download_data(data_dir="./data"):
  """
  Download IWAE data at specified location
  """
  # Links and Paths
  omniglot_link = "https://github.com/yburda/iwae/raw/master/datasets/OMNIGLOT/chardata.mat"
  omniglot_file_path = data_dir + "/OMNIGLOT/chardata.mat"

  mnist_train_images_link = "http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz"
  mnist_train_labels_link = "http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz"
  mnist_test_images_link = "http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz"
  mnist_test_labels_link = "http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz"
  mnist_path = data_dir + "/MNIST/"

  bmnist_train_link = "http://www.cs.toronto.edu/~larocheh/public/datasets/binarized_mnist/binarized_mnist_train.amat"
  bmnist_val_link = "http://www.cs.toronto.edu/~larocheh/public/datasets/binarized_mnist/binarized_mnist_valid.amat"
  bmnist_test_link = "http://www.cs.toronto.edu/~larocheh/public/datasets/binarized_mnist/binarized_mnist_test.amat"
  bmnist_path = data_dir + "/BinaryMNIST/"

  if not os.path.exists(data_dir):
    os.mkdir(data_dir)
  # Create data directory
  os.mkdir(mnist_path)
  os.mkdir(data_dir + "/OMNIGLOT")
  os.mkdir(data_dir + "/BinaryMNIST")
  # Download omniglot data
  wget.download(omniglot_link, out=omniglot_file_path)
  # Download mnist data
  wget.download(mnist_train_images_link, out=mnist_path)
  wget.download(mnist_train_labels_link, out=mnist_path)
  wget.download(mnist_test_images_link, out=mnist_path)
  wget.download(mnist_test_labels_link, out=mnist_path)
  # Unzip mnist data
  for filename in os.listdir(mnist_path):
    f = os.path.join(mnist_path, filename)
    unzip_gz(f)
    os.remove(f)
  # Download bmnist data
  wget.download(bmnist_train_link, out=bmnist_path)
  wget.download(bmnist_val_link, out=bmnist_path)
  wget.download(bmnist_test_link, out=bmnist_path)




